### ISSUE TITLE
"Delete All" and Individual "X" for deletion disappear

### ISSUE THREAD

**Issue by etrigan63** [phuhl/linux_notification_center#140] opened 2021-01-22 14:20 UTC
When the Notification Center has a large number of notifications, the "Delete All" and "X" for individual message deletion disappear from view. The button is still functional if you are lucky enough to hit it. Controls return if process is restarted (which causes stored notification to be erased).

**Comment by phuhl** [comment] 2021-01-22 14:24
Thanks for reporting. Just to clarify, do all "X" buttons disapear, or only a few? 

Could you provide a (redacted) screenshot?

Which version are you on?

**Comment by etrigan63** [comment] 2021-01-22 14:58
All of the buttons.
I am on 1.7.3-2 AUR (bin version)
When it accumulates enough messages, I will take a screenshot.
Are there any sample CSS files? I was hoping some folks would post theirs but no one has as yet.

**Comment by phuhl** [comment] 2021-01-22 15:04
I think, the issue you are facing is a duplicate of #103. Might that be possible? The bin version in the AUR does not have the fix, yet AFAIK.

Also the bin version does not have the new CSS features, yet. The git version does, though and it contains [this](https://github.com/phuhl/linux_notification_center/blob/master/style.css) file which also should be installed to your config directory as deadd.css (except, deadd.css exists already). That css file produces the white styled notification center as can be seen in some screenshots in the README.

I don't have any other CSS files, yet, partially because that feature is relatively new, partially, because there is currently no channel where people could submit them.

If you have a good idea, where/how an exchange of styles could be made possible, I am all ears. I was thinking, maybe we could dedicate a page in the github wiki (I think, it doesn't contain anything, yet) for this.

**Comment by etrigan63** [comment] 2021-01-22 15:12
Trying the git version.

**Comment by etrigan63** [comment] 2021-01-22 16:39
Removed the bin version. Deleted the config and css files to start clean. Git version did not install new ones (just like the bin). Had to manually copy from style.css and from the conf code in the notes (there is no conf file in the github). Will see what happens after lunch.

**Comment by phuhl** [comment] 2021-01-22 16:44
Hm, strange that the css file was not copied. This is trackend in #132 but I thought, it was resolved but not yet confirmed.

Concerning the config file, yes, no default config file should be created, currently. But the dnc should run without one just fine, I think.

Btw, just thinking of it: If you want to go totally crazy, you could beta test the new config file format from PR #138. It brings a lot of enhancements and new features, is not yet merged though. But any notes on that are of course appreciated in the PR

**Comment by etrigan63** [comment] 2021-01-22 19:56
The git version seems to have addressed the button issue. I will monitor and see if it reoccurs. I will await the merger of PR#138 before I test that. I find YAML annoying beyond words.

**Comment by phuhl** [comment] 2021-01-22 22:31
Ok, feel free to reopen, should the issue persist

**Closed by phuhl** 2021-01-22 22:31 UTC
