### ISSUE TITLE
Toggling DNG makes it appear in the middle of the screen and it appears to be ignoring the margins set in dead.conf

### ISSUE THREAD

**Issue by deadbody13** [phuhl/linux_notification_center#147] opened 2021-01-25 01:50 UTC
I went from i3 to Sway (xorg to Wayland) and now the DNG is behaving noticeably different. The notifications show up in the middle of the active screen and the notification center itself will always show up in the center of the screen it's assigned to.

Distro: Arch Linux
DE: Sway
[deadd.conf](https://gitlab.com/Deadbody13/configfiles/-/blob/master/deadd/deadd.conf)
[deadd.css](https://gitlab.com/Deadbody13/configfiles/-/blob/master/deadd/deadd.css)

**Comment by phuhl** [comment] 2021-01-25 13:47
This is more or less a duplicate of #26. We don't currently have wayland support.

In that thread there might have been a solution for your problem posted, too:

>The way they're using it is by setting GDK_BACKEND=x11 which forces it to use xwayland. While this would work, it isn't "correct" for wlroots compositors, and just tends to either look bad, break, or not function at all. Actual wlroots support would be great. There's a gtk-layer-shell project that you could look into, or the actual wlroots protocol itself

I hope, that helps. Anyways, as we don't have wayland support build in, currently, I will close this issue. PRs are welcome to improve the wayland situation

**Closed by phuhl** 2021-01-25 13:47 UTC
