### ISSUE TITLE
Aur package does not build

### ISSUE THREAD

**Issue by Xananax** [phuhl/linux_notification_center#4] opened 2019-01-20 07:39 UTC
When trying to build (with `yay`), I get:

```sh
==> Starting build()...
stack setup
stack will use a sandboxed GHC it installed
<snip>...</snip>
Building library for linux-notification-center-1.0.1..
[ 1 of 11] Compiling Helpers          ( src/Helpers.hs, .stack-work/dist/x86_64-linux-tinfo6/Cabal-2.2.0.1/build/Helpers.o )
                                             
/home/xananax/.cache/yay/deadd-notification-center/src/linux_notification_center-1.0.1/src/Helpers.hs:4:1: warning: [-Wdeprecations]
    Module ‘Control.Monad.Error’ is deprecated:
      Use "Control.Monad.Except" instead     
  |                                          
4 | import qualified Control.Monad.Error as Error
  | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
                                             
/home/xananax/.cache/yay/deadd-notification-center/src/linux_notification_center-1.0.1/src/Helpers.hs:12:37: warning: [-Wdeprecations]
    In the use of ‘runErrorT’                
    (imported from Control.Monad.Error, but defined in Control.Monad.Trans.Error):
    Deprecated: "Use Control.Monad.Trans.Except instead"
   |                                         
12 |   $ fromEither (Right defaultVal) $ Error.runErrorT $ CF.get conf sec opt
   |                                     ^^^^^^^^^^^^^^^
[ 2 of 11] Compiling NotificationCenter.Glade ( src/NotificationCenter/Glade.hs, .stack-work/dist/x86_64-linux-tinfo6/Cabal-2.2.0.1/build/NotificationCenter/Glade.o )
<command line>: can't load .so/.DLL for: /home/xananax/.stack/snapshots/x86_64-linux-tinfo6/lts-12.19/8.4.4/lib/x86_64-linux-ghc-8.4.4/libHSgi-gtk-3.0.26-Go8bObhKK4v7CUOOhG6z4k-ghc8.4.4.so (/home/xananax/.stack/snapshots/x86_64-linux-tinfo6/lts-12.19/8.4.4/lib/x86_64-linux-ghc-8.4.4/libHSgi-gtk-3.0.26-Go8bObhKK4v7CUOOhG6z4k-ghc8.4.4.so: undefined symbol: gtk_cell_accessible_parent_get_row_header_cells)
Completed 4 action(s).                       

--  While building package linux-notification-center-1.0.1 using:
      /home/xananax/.stack/setup-exe-cache/x86_64-linux-tinfo6/Cabal-simple_mPHDZzAJ_2.2.0.1_ghc-8.4.4 --builddir=.stack-work/dist/x86_64-linux-tinfo6/Cabal-2.2.0.1 build lib:linux-notification-center exe:deadd-notification-center --ghc-options " -ddump-hi -ddump-to-file -fdiagnostics-color=always"
    Process exited with code: ExitFailure 1
make: *** [Makefile:12: stack] Error 1
==> ERROR: A failure occurred in build().
    Aborting...
Error making: deadd-notification-center
```

Any idea?

**Comment by phuhl** [comment] 2019-01-21 21:15
Ok, I was able to reproduce the issue and it looks like it is a `libgtk` issue and we will have to wait for a fix to come out. [Here](https://github.com/haskell-gi/haskell-gi/issues/212) the same issue is described and they filed a bugreport [here](https://bugzilla.opensuse.org/show_bug.cgi?id=1121456). I will check back on this soon.

**Comment by Xananax** [comment] 2019-01-22 02:30
Sorry it was silly of me to not provide more details, and thanks for putting up with it (I must've been busy and didn't pay attention). As you correctly guessed, I use Arch.

Will be waiting for the fix!

**Comment by LeifW** [comment] 2019-01-26 22:06
As a workaround, removing references to `get_row_header_cells` and `get_column_header_cells` from /usr/share/gir-1.0/Gtk-3.0.gir (it's just an XML file) and rebuilding gi-gtk works. More background on that here: https://github.com/haskell-gi/haskell-gi/issues/212#issuecomment-452194955
Filed a ticket against the Arch gtk3 package; feel free to follow / vote for it: https://bugs.archlinux.org/task/61486?project=1&string=gtk3

**Comment by phuhl** [comment] 2019-02-11 21:46
I saw that the bug was fixed in the open suse package (if anyone here is waiting for that one), the Arch package is not fixed, yet :(

**Comment by wtfdewuno** [comment] 2019-02-13 13:46
> I saw that the bug was fixed in the open suse package (if anyone here is waiting for that one), the Arch package is not fixed, yet :(

https://i.imgur.com/ydOeOes.png

**Comment by phuhl** [comment] 2019-02-17 14:23
@wtfdewuno 
> > I saw that the bug was fixed in the open suse package (if anyone here is waiting for that one), the Arch package is not fixed, yet :(
> 
> this screenshot is coming from Arch
> 
> https://i.imgur.com/ydOeOes.png

I don't think that this is related to this issue. If you think this is a bug by deadd-notification-center, please open a new issue and give a few more details on your setup (OS, stack version, complete output of build, ...).

**Comment by Marko1000Marko** [comment] 2019-03-06 19:25
Latest version builds successfully for me

**Comment by phuhl** [comment] 2019-04-18 10:22
Looks like it works again (https://bugs.archlinux.org/task/61486)

**Closed by phuhl** 2019-04-18 10:22 UTC
